[package]
name = "guile-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
guile-rs-sys = { workspace = true }
bitflags = "2.10.0"
libc = "0.2.177"
tokio = { workspace = true }
parking_lot = { version = "0.12.5", features = ["send_guard"] }
futures = { workspace = true }