[package]
name = "koru-modules"
version = "0.1.0"
edition = "2024"

[dependencies]
mlua = { workspace = true }

[features]
default = []
luajit = ["mlua/luajit", "mlua/module"]
lua52 = ["mlua/lua51", "mlua/module"]